In [2]:
# Ritesh Bhingare 
# Roll no: 19
# Batgch : TA1
# Assignment 1: Numpy Basics

In [7]:
import numpy as np

In [8]:
arr1 = np.array([1, 2, 3])
arr1

array([1, 2, 3])

In [9]:
# Array Dimension
array1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array1)
print(f"Dimension of array is : {array1.ndim}")


[[1 2 3]
 [4 5 6]
 [7 8 9]]
Dimension of array is : 2


In [ ]:
# Array Indexing 
array2 = np.array([11,12,13,14,15,16])
print(array2)
print(array2[1])
print(array2[-1])
print(array2[-4])


[11 12 13 14 15 16]
12
16
[16 15 14 13 12 11]
13


In [12]:
# Array arrange and reshape
array3 = np.arange(1,10)
array3.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
#Array Concatenation
arr4 = np.array([[1, 2, 3], [4, 5, 6]])
arr5 = np.array([[7, 8, 9], [10, 11, 12]])
a=arr4+arr5
print(arr4)
print(arr5)
print('-'*20)
print(a)


[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
--------------------
[[ 8 10 12]
 [14 16 18]]


In [15]:
# Array Arthimetric Operations
arr6 = np.array([[1, 2, 3], [4, 5, 6]])
arr7 = np.array([[7, 8, 9], [10, 11, 12]])
arr8 = arr6 * arr7
print(arr6)
arr9 = arr6 - arr7
print(arr9)
print('-'*20)
arr10 = arr6 * arr7
print(arr10)
print('-'*20)
arr11 = arr6 / arr7
print(arr11)
print('-'*20)
arr12 = arr6 ** arr7
print(arr12)
print('-'*20)


[[1 2 3]
 [4 5 6]]
[[-6 -6 -6]
 [-6 -6 -6]]
--------------------
[[ 7 16 27]
 [40 55 72]]
--------------------
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]
--------------------
[[         1        256      19683]
 [   1048576   48828125 2176782336]]
--------------------


In [23]:
# Self learning
print(array1.argmax())
print(array2.argmin())


8
0


In [20]:
?array1  

Type:        ndarray
String form:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Length:      3
File:        c:\users\rites\appdata\local\programs\python\python313\lib\site-packages\numpy\__init__.py
Docstring:  
ndarray(shape, dtype=float, buffer=None, offset=0,
        strides=None, order=None)

An array object represents a multidimensional, homogeneous array
of fixed-size items.  An associated data-type object describes the
format of each element in the array (its byte-order, how many bytes it
occupies in memory, whether it is an integer, a floating point number,
or something else, etc.)

Arrays should be constructed using `array`, `zeros` or `empty` (refer
to the See Also section below).  The parameters given here refer to
a low-level method (`ndarray(...)`) for instantiating an array.

For more information, refer to the `numpy` module and examine the
methods and attributes of an array.

Parameters
----------
(for the __new__ method; see Notes below)

shape : tuple of ints
    Shape of created array.